# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['hashharvest/main.py'],
    pathex=[],
    binaries=[],
    datas=[('README.md', '.')],
    hiddenimports=[
        'PyQt5.sip',
        'vt',                          # VirusTotal lookup — lazily imported, so declare it
        'keyring.backends.Windows',    # keychain storage backend (Windows Credential Manager)
        'win32ctypes.pywin32',         # provides pywintypes/win32cred for keyring's backend
        'win32ctypes.pywin32.pywintypes',
        'win32ctypes.pywin32.win32cred',
    ],
    hookspath=['scripts/pyi_hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # --- Heavy Qt5 modules not used by this app ---
        'PyQt5.QtWebEngine',
        'PyQt5.QtWebEngineWidgets',
        'PyQt5.QtWebEngineCore',
        'PyQt5.QtWebChannel',
        'PyQt5.QtWebSockets',
        'PyQt5.QtMultimedia',
        'PyQt5.QtMultimediaWidgets',
        'PyQt5.QtBluetooth',
        'PyQt5.QtNetwork',
        'PyQt5.QtNfc',
        'PyQt5.QtPositioning',
        'PyQt5.QtLocation',
        'PyQt5.QtQml',
        'PyQt5.QtQuick',
        'PyQt5.QtQuickWidgets',
        'PyQt5.QtSql',
        'PyQt5.QtSvg',
        'PyQt5.QtXml',
        'PyQt5.QtXmlPatterns',
        'PyQt5.QtDesigner',
        'PyQt5.QtHelp',
        'PyQt5.QtTest',
        'PyQt5.Qt3DAnimation',
        'PyQt5.Qt3DCore',
        'PyQt5.Qt3DExtras',
        'PyQt5.Qt3DInput',
        'PyQt5.Qt3DLogic',
        'PyQt5.Qt3DRender',
        'PyQt5.QtOpenGL',
        'PyQt5.QtSensors',
        'PyQt5.QtSerialPort',
        'PyQt5.QtTextToSpeech',
        'PyQt5.QtChart',
        'PyQt5.QtDataVisualization',
        'PyQt5.QtPurchasing',
        'PyQt5.QtRemoteObjects',
        # --- Unused stdlib ---
        'tkinter',
        '_tkinter',
        'unittest',
        'pydoc',
        'doctest',
        'difflib',
        'distutils',
        # NOTE: do not exclude 'email' — http.client and aiohttp (vt-py) need it.
        'ftplib',
        'imaplib',
        'mailbox',
        'smtpd',
        'smtplib',
        'telnetlib',
        'xmlrpc',
        'curses',
        # --- Packages that may get pulled in transitively ---
        'lxml',           # pypdf has optional lxml dep; triggers deep recursion in hooks
        'setuptools',
        'pkg_resources',
        'numpy',
        'pandas',
        'scipy',
        'matplotlib',
        'PIL',
        'Pillow',
        'IPython',
        'cryptography',
        'OpenSSL',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='HashHarvest',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=['vcruntime140.dll', 'python3*.dll'],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
